import React, { useState, useEffect, useRef } from 'react';
import { ChevronLeft, Send, Smile, ShieldAlert, Star, Flag, Info, Lock, Copy } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { Avatar, AvatarStack, ActivityArt, EmptyState, Sheet, SpotMeter, sameId, categoryFor } from './DesignKit';
export function ChatView() {
  const { plans, activeChatPlanId, setActiveChatPlanId, currentUser, getUserById, sendMessage, triggerEmergencySOS, setShowKarmaModal, setKarmaReviewPlan, setReportingUser, setSelectedPlanForDetail, setActiveTab, markChatAsRead } = useApp();
  const [input, setInput] = useState('');
  const [emoji, setEmoji] = useState(false);
  const [sos, setSos] = useState(null);
  const [copied, setCopied] = useState(false);
  const [shareError, setShareError] = useState('');
  const messageArea = useRef(null);
  const plan = plans.find(p => sameId(p.id, activeChatPlanId));
  const member = plan?.acceptedMembers?.some(id => sameId(id, currentUser.id));
  useEffect(() => { messageArea.current?.scrollTo({ top: messageArea.current.scrollHeight, behavior: 'smooth' }); }, [plan?.messages]);
  useEffect(() => { 
    setInput(''); 
    setEmoji(false);
    if (activeChatPlanId && markChatAsRead) {
      markChatAsRead(activeChatPlanId);
    }
  }, [activeChatPlanId, plan?.messages?.length]);
  const userPlans = plans.filter(p => p.acceptedMembers?.some(id => sameId(id, currentUser.id)));
  if (!plan || !member) return <div className="screen chat-list-screen"><div className="screen-heading"><span className="eyebrow">THE WEEKEND STARTS WITH A HELLO</span><h1>💬 Crew Chats</h1><p>A little coordination. A lot to look forward to.</p></div>{userPlans.length ? <div className="chat-list">{userPlans.map(p => <button className="chat-list-item" key={p.id} onClick={() => setActiveChatPlanId(p.id)}><span className="chat-list-art" style={{ background: categoryFor(p.category).color }}><ActivityArt type={p.category} size={45} /></span><span><strong>{p.title}</strong><small>{p.venueName}</small><span className={`pill ${p.status === 'LOCKED_CHAT_ACTIVE' ? 'pill-mint' : 'pill-sand'}`}>{p.status === 'LOCKED_CHAT_ACTIVE' ? '💬 Chat unlocked' : `🔒 ${p.acceptedMembers.length}/${p.targetCapacity} confirmed`}</span></span><span className="chat-list-arrow">↗</span></button>)}</div> : <EmptyState title="Good conversations are coming" description="Join a crew first. When your little group is confirmed, your chat will open here." art="cafe" action={() => setActiveTab('explore')} actionLabel="Find your weekend crew" />}</div>;
  const unlocked = plan.status === 'LOCKED_CHAT_ACTIVE';
  const host = sameId(plan.hostId, currentUser.id);
  const submit = e => { e.preventDefault(); if (!input.trim() || !unlocked) return; sendMessage(plan.id, input); setInput(''); setEmoji(false); };
  if (!unlocked) return <div className="screen waiting-screen"><button className="back-link" onClick={() => setActiveChatPlanId(null)}><ChevronLeft size={18} />Back to Chats</button><div className="waiting-card"><div className="waiting-lock"><Lock size={37} /></div><span className="eyebrow">A LITTLE PATIENCE. A GREAT LITTLE CREW.</span><h1>{plan.title}</h1><p>Your chat opens when all {plan.targetCapacity} spots are confirmed.</p><div className="waiting-spots"><strong>{plan.acceptedMembers.length}/{plan.targetCapacity} confirmed</strong><SpotMeter filled={plan.acceptedMembers.length} total={plan.targetCapacity} /></div><AvatarStack ids={plan.acceptedMembers} size={43} /><p className="footnote">Good company is worth the wait ✧</p><button className="text-button" onClick={() => setSelectedPlanForDetail(plan)}>View your plan ↗</button></div></div>;
  return <div className="crew-chat"><header className="chat-header"><button className="icon-button" onClick={() => setActiveChatPlanId(null)} aria-label="Back to crew chats"><ChevronLeft size={23} /></button><ActivityArt type={plan.category} size={31} /><div><h1>{plan.title}</h1><span>{plan.acceptedMembers.length} lovely people · {plan.neighborhood}</span></div><button className="icon-button" aria-label="View crew plan" onClick={() => setSelectedPlanForDetail(plan)}><Info size={20} /></button></header><div className="chat-tools"><button onClick={() => { setKarmaReviewPlan(plan); setShowKarmaModal(true); }}><Star size={13} />Rate your meetup</button><button onClick={async () => { setSos(await triggerEmergencySOS(plan)); setCopied(false); setShareError(''); }}><ShieldAlert size={14} />Safety & SOS</button></div><div className="chat-messages" ref={messageArea}><div className="chat-welcome"><span>☀ Your crew is together!</span><p>Say hi and let everyone know when you’ll arrive.</p></div>{plan.messages?.map(msg => {
    if (msg.isSystem) return <div className="system-message" key={msg.id}>{msg.content}</div>;
    const me = sameId(msg.senderId, currentUser.id), sender = getUserById(msg.senderId);
    return <div className={`chat-message ${me ? 'own' : ''}`} key={msg.id}>{!me && <Avatar user={sender} size={28} />}<div className="message-content">{!me && <div className="message-author"><span>{sender.name}</span><button onClick={() => setReportingUser({ user: sender, planId: plan.id })} aria-label={`Report ${sender.name}`}><Flag size={11} /></button></div>}<div className="message-bubble">{msg.content}</div><span className="message-time">{msg.timestamp}</span></div></div>;
  })}</div><div className="chat-unlocked"><span>💬 <strong>Chat unlocked!</strong></span><small>Your crew is confirmed. Let’s make a plan.</small></div>{emoji && <div className="emoji-picker">{['👋', '☕', '🙌', '😍', '🎉', '❤️', '😂', '☀️'].map(e => <button key={e} aria-label={`Add ${e} to message`} onClick={() => { setInput(i => i + e); setEmoji(false); }}>{e}</button>)}</div>}<form className="chat-composer" onSubmit={submit}><div><input aria-label="Message your crew" placeholder="Type a message…" value={input} onChange={e => setInput(e.target.value)} maxLength={2000} /><button type="submit" disabled={!input.trim()} aria-label="Send message"><Send size={17} fill="currentColor" /></button></div><button type="button" className="emoji-button" onClick={() => setEmoji(v => !v)} aria-label="Choose an emoji" aria-expanded={emoji}><Smile size={22} /></button></form>{sos && <Sheet title="Your safety summary" onClose={() => setSos(null)}><div className="sheet-title"><h2>🛡 Your safety summary</h2><p>Copy your meetup details to share with a trusted contact.</p></div><div className="sos-summary">{sos}</div><div className="sos-actions"><button className="button button-green wide-button" onClick={async () => { try { await navigator.clipboard.writeText(sos); setCopied(true); } catch { setShareError('Copy is unavailable. Select and copy the details above.'); } }}><Copy size={16} />{copied ? 'Copied ✓' : 'Copy meetup details'}</button>{shareError && <p className="footnote">{shareError}</p>}</div></Sheet>}</div>;
}
