import React, { useState } from 'react';
import { Navigation, MapPin, ShieldCheck, Radio, ChevronDown, Plus } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { calculateDistanceKm, PASSION_TO_CATEGORY_MAP } from '../venueData';
import { ActivityArt, Avatar, CityPicker, Sheet, EmptyState, CATEGORIES, categoryFor, trustScore, sameId } from './DesignKit';
export { PASSION_TO_CATEGORY_MAP } from '../venueData';
export function SquadRadarView() {
  const { radarMembers, selectedCity, isRadarBroadcastOn, setIsRadarBroadcastOn, sendCrewInvite, plans, currentUser, userCoords, isLocating, requestLiveLocation, setShowCreateModal, requireVerification, sendWave, hasWavedAt, hasReceivedWaveFrom, isMutualWave, blockedUserIds, getUserById, setActiveTab } = useApp();
  const [radius, setRadius] = useState(15);
  const [women, setWomen] = useState(false);
  const [category, setCategory] = useState('all');
  const [candidateId, setCandidateId] = useState(null);
  const [invitePlan, setInvitePlan] = useState('');
  const [invited, setInvited] = useState(false);
  const distance = member => member.lat && member.lng ? calculateDistanceKm(userCoords.lat, userCoords.lng, member.lat, member.lng) : member.distanceKm;
  const nearby = radarMembers.filter(member => {
    if (sameId(member.id, currentUser.id) || blockedUserIds?.includes(member.id)) return false;
    if (member.city && member.city.toLowerCase() !== selectedCity.toLowerCase()) return false;
    if (women && (member.gender !== 'female' || trustScore(member) === 0)) return false;
    if (category !== 'all' && member.primaryCat !== category && !(member.interests || []).some(p => PASSION_TO_CATEGORY_MAP[p] === category)) return false;
    const km = distance(member);
    return km == null || km <= radius;
  });
  const candidateMember = radarMembers.find(m => m.id === candidateId);
  const candidateUser = candidateId && getUserById ? getUserById(candidateId) : null;
  const candidate = candidateMember ? { 
    ...candidateMember, 
    ...candidateUser,
    phoneVerified: Boolean(candidateMember.phoneVerified || candidateUser?.phoneVerified || candidateUser?.phone_verified),
    idVerified: Boolean(candidateMember.idVerified || candidateUser?.idVerified || candidateUser?.id_verified || candidateMember.avatar?.startsWith('data:image') || candidateUser?.avatar?.startsWith('data:image')),
    linkedin_verified: Boolean(candidateMember.linkedin_verified || candidateUser?.linkedin_verified || candidateUser?.linkedInVerified),
    bio: candidateMember.bio || candidateUser?.bio || ''
  } : null;
  const openPlans = plans.filter(p => sameId(p.hostId, currentUser.id) && p.status !== 'COMPLETED' && (p.acceptedMembers?.length || 0) < p.targetCapacity && (!p.womenOnly || (candidate?.gender === 'female' && trustScore(candidate) > 0)));
  const open = member => { setCandidateId(member.id); setInvitePlan(''); setInvited(false); };
  const wave = () => requireVerification(() => sendWave(candidate.id), 'radar_wave');
  return <div className="screen radar-screen"><div className="screen-heading"><span className="eyebrow">GOOD COMPANY, AROUND THE CORNER</span><h1>Who’s Around? <span>🧭</span></h1><p>Find people who weekend like you.</p></div><div className="radar-toolbar"><CityPicker /><button className="icon-button gps-button" onClick={requestLiveLocation} disabled={isLocating} aria-label="Use my current location"><Navigation size={18} className={isLocating ? 'animate-spin' : ''} /></button><button className={`broadcast-toggle ${isRadarBroadcastOn ? 'on' : ''}`} onClick={() => setIsRadarBroadcastOn(v => !v)} aria-pressed={isRadarBroadcastOn}><i />{isRadarBroadcastOn ? 'Visible' : 'Hidden'}</button></div><div className="radar-filters"><div className="radius-switch">{[5, 15].map(km => <button key={km} className={radius === km ? 'selected' : ''} onClick={() => setRadius(km)} aria-pressed={radius === km}>{km} km</button>)}</div><button className={`filter-pill ${women ? 'selected-pink' : ''}`} onClick={() => setWomen(v => !v)} aria-pressed={women}><ShieldCheck size={13} />Women only</button><span className="radar-category"><select aria-label="Filter radar by passion" value={category} onChange={e => setCategory(e.target.value)}><option value="all">All passions</option>{CATEGORIES.map(cat => <option key={cat.id} value={cat.id}>{cat.label}</option>)}</select><ChevronDown size={13} /></span></div>
    <div className="radar-content"><div className={`radar-map ${nearby.length ? '' : 'radar-empty'}`} aria-label="Nearby community radar"><div className="radar-ring outer-ring" /><div className="radar-ring middle-ring" /><div className="radar-ring inner-ring" /><span className="ring-label outer-label">City-wide · 5–15 km</span><span className="ring-label middle-label">Quick Ride 🛺</span><span className="ring-label inner-label">Walking Distance 🚶</span><button type="button" className="radar-you" onClick={() => setActiveTab('profile')} title="Go to your profile" style={{ background: 'none', border: 'none', padding: 0, cursor: 'pointer' }} aria-label="Go to your profile"><span className="you-halo" /><Avatar user={currentUser} size={62} /><span>You are here 📍</span></button>{nearby.slice(0, 9).map((member, index) => { const angle = (index * 137.5 + 220) * Math.PI / 180; const km = distance(member); const r = km < 2 ? 25 : km < 5 ? 37 : 44; const cat = categoryFor(member.primaryCat); return <button className="radar-member" key={member.id} style={{ left: `${50 + Math.cos(angle) * r}%`, top: `${50 + Math.sin(angle) * r}%`, '--member-color': cat.color }} onClick={() => open(member)} aria-label={`View ${member.name}, ${km != null ? km + ' kilometres away' : 'nearby'}`}><Avatar user={member} size={47} />{hasReceivedWaveFrom(member.id) && <span className="member-wave">👋</span>}<span className="radar-member-label">{member.name?.split(' ')[0]}{km != null && ` · ${km} km`}</span></button>; })}{!nearby.length && <div className="radar-scanning"><ActivityArt type="binoculars" size={83} /><span>Scanning for your people…</span></div>}</div>
    <div className="radar-nearby">{nearby.length ? <><p className="radar-instruction">Tap a member to say hi 👋<span>{nearby.length} people in your orbit</span></p><div className="nearby-list">{nearby.map(member => <button key={member.id} onClick={() => open(member)}><Avatar user={member} size={38} /><div><strong>{member.name}</strong><span>{(member.interests || [member.primaryActivity]).filter(Boolean).slice(0, 2).join(' · ')}</span></div><span className="nearby-wave">👋</span></button>)}</div></> : <div className="radar-empty-copy"><h2>Your Squad Radar is Scanning…</h2><p>Nearby members will appear as they open the app in {selectedCity}.<br />A good weekend is worth the wait.</p></div>}
    </div></div>{candidate && <Sheet title={`${candidate.name}'s profile`} className="candidate-sheet" onClose={() => setCandidateId(null)}><div className="candidate-banner" /><div className="candidate-identity"><div className="candidate-avatar-ring"><Avatar user={candidate} size={86} /></div><h1>{candidate.name}</h1><div className="passion-tags">{(candidate.interests || [candidate.primaryActivity]).filter(Boolean).map((p, i) => <span className={`pill passion-color-${i % 4}`} key={p}>{p}</span>)}</div></div><div className="candidate-body"><div className="section-row"><h3>Trust</h3><span className="pill pill-sand">{trustScore(candidate) > 0 ? '🛡 Trusted' : 'New Member'}</span></div><div className="candidate-trust-bar"><i style={{ width: `${trustScore(candidate)}%` }} /><strong>{trustScore(candidate)}%</strong></div><h3 className="section-title">Bio</h3><p className="candidate-bio">{candidate.bio || `Up for ${candidate.primaryActivity || 'a good weekend'} and meeting a little crew in ${selectedCity}.`}</p><p className="candidate-location"><MapPin size={15} />{candidate.neighborhood || selectedCity}{distance(candidate) != null && ` · ${distance(candidate)} km away`}</p><h3 className="section-title">Say hi, the easy way</h3><button className="button button-purple wide-button" onClick={wave} disabled={hasWavedAt(candidate.id)}>{isMutualWave(candidate.id) ? '🤝 You both waved!' : hasWavedAt(candidate.id) ? '👋 Wave sent!' : hasReceivedWaveFrom(candidate.id) ? '👋 Wave back' : '👋 Interested in Similar Plans'}</button><p className="footnote">{hasWavedAt(candidate.id) && !isMutualWave(candidate.id) ? 'When they wave back, you can invite them to a plan.' : 'Shared plans make the best icebreakers.'}</p>{isMutualWave(candidate.id) && <><div className="mutual-wave"><h3>🤝 Squad Up!</h3><p>You’re both interested in similar plans!</p><button className="button button-yellow" onClick={() => { setCandidateId(null); requireVerification(() => setShowCreateModal(true), 'create_plan'); }}>📋 Create a Plan Together</button></div><label htmlFor="invite-plan" className="section-title">Invite to Your Weekend Crew</label>{openPlans.length ? <><select id="invite-plan" className="invite-selector" value={invitePlan} onChange={e => setInvitePlan(e.target.value)}><option value="">Pick your open plan</option>{openPlans.map(plan => <option key={plan.id} value={plan.id}>{plan.title}</option>)}</select><button className="button button-green wide-button" disabled={!invitePlan || invited} onClick={() => requireVerification(() => { sendCrewInvite(candidate.id, invitePlan); setInvited(true); }, 'radar_invite')}>{invited ? 'Added to your crew ✓' : 'Invite to crew 🎟️'}</button></> : <p className="quiet-box">Create a new plan to bring your little crew together.</p>}</>}</div></Sheet>}
  </div>;
}
