// Opt-in verified community members broadcasting weekend availability
export const NEARBY_RADAR_MEMBERS = [
  // Bengaluru
  {
    id: 'rad_blr_1',
    name: 'Priya Sharma',
    age: 26,
    gender: 'female',
    city: 'Bengaluru',
    neighborhood: 'Indiranagar (100ft Rd)',
    role: 'Product Designer',
    company: 'Swiggy',
    linkedInVerified: true,
    workEmailVerified: true,
    idVerified: true,
    karmaScore: 5.0,
    meetupsAttended: 6,
    bio: 'Specialty coffee enthusiast, weekend pottery dabbler, and amateur runner at Cubbon Park.',
    primaryActivity: '☕ Cafe & Brunch',
    primaryCat: 'cafe',
    interests: ['cafe', 'arts', 'sports'],
    isAvailableThisWeekend: true,
    distanceKm: 0.9,
    latOffset: 0.006,
    lngOffset: 0.007,
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80'
  },
  {
    id: 'rad_blr_2',
    name: 'Rahul Mehta',
    age: 27,
    gender: 'male',
    city: 'Bengaluru',
    neighborhood: 'Koramangala 4th Block',
    role: 'Backend Engineer',
    company: 'Razorpay',
    linkedInVerified: true,
    workEmailVerified: true,
    idVerified: true,
    karmaScore: 4.9,
    meetupsAttended: 4,
    bio: 'Intermediate badminton player (Yonex Astrox). Always up for weekend turf games and craft beers at Toit.',
    primaryActivity: '🏸 Badminton Doubles',
    primaryCat: 'sports',
    interests: ['sports', 'cafe', 'concert'],
    isAvailableThisWeekend: true,
    distanceKm: 1.4,
    latOffset: -0.008,
    lngOffset: -0.005,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80'
  },
  {
    id: 'rad_blr_3',
    name: 'Ananya Deshmukh',
    age: 25,
    gender: 'female',
    city: 'Bengaluru',
    neighborhood: 'HSR Layout Sector 3',
    role: 'Growth Lead',
    company: 'CRED',
    linkedInVerified: true,
    workEmailVerified: true,
    idVerified: true,
    karmaScore: 5.0,
    meetupsAttended: 8,
    bio: 'Standup comedy nerd (Tanmay/Bassi fan). Looking for open mic and comedy trial show crews this Saturday.',
    primaryActivity: '🎭 Standup & Open Mics',
    primaryCat: 'comedy',
    interests: ['comedy', 'cafe', 'concert'],
    isAvailableThisWeekend: true,
    distanceKm: 2.1,
    latOffset: 0.012,
    lngOffset: -0.011,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80'
  },
  {
    id: 'rad_blr_4',
    name: 'Vikram Sengupta',
    age: 29,
    gender: 'male',
    city: 'Bengaluru',
    neighborhood: 'Whitefield / EPIP Zone',
    role: 'Data Scientist',
    company: 'Microsoft',
    linkedInVerified: true,
    workEmailVerified: true,
    idVerified: true,
    karmaScore: 4.8,
    meetupsAttended: 3,
    bio: 'Live acoustic gigs & heritage walks. Looking to join a casual weekend music or photography crew.',
    primaryActivity: '🎵 Live Music & Gigs',
    primaryCat: 'concert',
    interests: ['concert', 'hike', 'cafe'],
    isAvailableThisWeekend: true,
    distanceKm: 3.5,
    latOffset: -0.018,
    lngOffset: 0.015,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80'
  },
  {
    id: 'rad_blr_5',
    name: 'Sneha Kulkarni',
    age: 24,
    gender: 'female',
    city: 'Bengaluru',
    neighborhood: 'Lavelle Road / Ashok Nagar',
    role: 'Architect & Urban Planner',
    company: 'Studio Decode',
    linkedInVerified: true,
    workEmailVerified: true,
    idVerified: true,
    karmaScore: 5.0,
    meetupsAttended: 5,
    bio: 'Weekend watercoloring, botanical garden walks, and exploring vintage book cafes.',
    primaryActivity: '🏺 Art & Workshops',
    primaryCat: 'arts',
    interests: ['arts', 'cafe', 'hike'],
    isAvailableThisWeekend: true,
    distanceKm: 1.8,
    latOffset: 0.009,
    lngOffset: -0.008,
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80'
  },

  // Mumbai
  {
    id: 'rad_mum_1',
    name: 'Tanvi Kapoor',
    age: 27,
    gender: 'female',
    city: 'Mumbai',
    neighborhood: 'Pali Hill, Bandra West',
    role: 'Brand Manager',
    company: 'Nykaa',
    linkedInVerified: true,
    workEmailVerified: true,
    idVerified: true,
    karmaScore: 5.0,
    meetupsAttended: 7,
    bio: 'Subko sourdough lover & Sunset jogger at Bandstand. Looking for Sunday brunch hangouts.',
    primaryActivity: '☕ Brunch & Bakehouse',
    primaryCat: 'cafe',
    interests: ['cafe', 'sports'],
    isAvailableThisWeekend: true,
    distanceKm: 1.1,
    latOffset: 0.005,
    lngOffset: 0.006,
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80'
  },
  {
    id: 'rad_mum_2',
    name: 'Rohan Varma',
    age: 28,
    gender: 'male',
    city: 'Mumbai',
    neighborhood: 'BKC / Bandra East',
    role: 'Investment Banker',
    company: 'Morgan Stanley',
    linkedInVerified: true,
    workEmailVerified: true,
    idVerified: true,
    karmaScore: 4.9,
    meetupsAttended: 4,
    bio: 'Looking for 5v5 turf football or comedy nights at The Habitat Khar.',
    primaryActivity: '🏸 Sports & Turf',
    primaryCat: 'sports',
    interests: ['sports', 'comedy', 'concert'],
    isAvailableThisWeekend: true,
    distanceKm: 2.3,
    latOffset: -0.010,
    lngOffset: 0.008,
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80'
  },

  // Delhi-NCR
  {
    id: 'rad_del_1',
    name: 'Kabir Singhal',
    age: 28,
    gender: 'male',
    city: 'Delhi-NCR',
    neighborhood: 'DLF Phase 4, Gurgaon',
    role: 'Product Manager',
    company: 'Zomato',
    linkedInVerified: true,
    workEmailVerified: true,
    idVerified: true,
    karmaScore: 5.0,
    meetupsAttended: 5,
    bio: 'Cyber Hub dinner plans, live standup, and early morning runs at Lodhi Garden.',
    primaryActivity: '🎭 Standup & Dinners',
    primaryCat: 'comedy',
    interests: ['comedy', 'cafe', 'sports'],
    isAvailableThisWeekend: true,
    distanceKm: 1.5,
    latOffset: 0.008,
    lngOffset: -0.007,
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80'
  },

  // Pune
  {
    id: 'rad_pun_1',
    name: 'Isha Joshi',
    age: 25,
    gender: 'female',
    city: 'Pune',
    neighborhood: 'Koregaon Park',
    role: 'UX Researcher',
    company: 'Persistent Systems',
    linkedInVerified: true,
    workEmailVerified: true,
    idVerified: true,
    karmaScore: 5.0,
    meetupsAttended: 4,
    bio: 'Specialty cafe hopping in KP, board game nights, and weekend Sinhagad treks.',
    primaryActivity: '☕ Cafe & Treks',
    primaryCat: 'cafe',
    interests: ['cafe', 'hike', 'arts'],
    isAvailableThisWeekend: true,
    distanceKm: 1.2,
    latOffset: 0.007,
    lngOffset: 0.005,
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80'
  }
];
